### ISSUE TITLE
【建议】在文档中指定要求的redis版本

### ISSUE THREAD

**Issue by DingGuodong** [TianPangJi/drf_admin#10]
需要在文档中指定要求的redis版本，比如要求redis版本3.x以上。

**Comment by TianPangJi** [comment]
> 需要在文档中指定要求的redis版本，比如要求redis版本3.x以上。

感谢指出问题，之前没有考虑版本问题，先已添加

**Comment by DingGuodong** [comment]
感谢，辛苦！
