### ISSUE TITLE
【咨询问题】在项目任意文件中调试（debug）变量

### ISSUE THREAD

**Issue by DingGuodong** [TianPangJi/drf_admin#11]
您好，我在使用这个项目时遇到了一个可能您认为比较简单的问题，想咨询一下，烦请能解答一下。

**问题：**
比如我想在`drf_admin/apps/oauth/views/home.py`文件里打印某变量的内容到console或文件。

除了使用print()函数能打印到console，应该如何编写代码呢？烦请提供一个简单的示例，谢谢！

**Comment by DingGuodong** [comment]
好似这样是可行的，但不知道是不是最佳实践。
```
import logging
logger = logging.getLogger('django.request')

# do this anywhere
logger.info("my debug" + str(variables))

```

**Comment by TianPangJi** [comment]
> 好似这样是可行的，但不知道是不是最佳实践。
> 
> ```
> import logging
> logger = logging.getLogger('django.request')
> 
> # do this anywhere
> logger.info("my debug" + str(variables))
> ```

如果单纯的调试的话，建议使用PyCharm的debug，并通过打断点的方式来调试，当然print也可以，但效果可能不如断点。
但如果想存储一些log记录有用的信息，建议使用logging，并且在dev.py配置文件中已配置了loggers，可以直接使用，或类型不满足可进行拓展。

**Comment by DingGuodong** [comment]
谢谢，感谢大佬解答！我已经放到[quick_start.md](https://github.com/DingGuodong/drf_admin/blob/master/doc/quick_start.md#django-%E9%99%A4%E9%94%99%E6%B5%8B%E8%AF%95--debug-in-django)文件中了。
