### ISSUE TITLE
联系求助

### ISSUE THREAD

**Issue by liu3734** [TianPangJi/drf_admin#13]
小老板，留个邮箱或者其他联系方式呀，我想参与这个的开发

**Comment by DingGuodong** [comment]
这是大佬的QQ群：1150323677，来这里聊天式交流吧！ 大佬github好似不是很活跃，所以。另外邮箱在代码里是有的。

**Comment by liu3734** [comment]
> 这是大佬的QQ群：1150323677，来这里聊天式交流吧！ 大佬github好似不是很活跃，所以。另外邮箱在代码里是有的。

谢谢咯

**Comment by TianPangJi** [comment]
这个就先close了
