### ISSUE TITLE
object-level / instance-level / row-level 权限控制

### ISSUE THREAD

**Issue by sdsy888** [TianPangJi/drf_admin#37]
看了项目的权限控制这块,我的理解是可以实现model-level的权限控制,请问能实现实例级别或者对象级别(数据库行级别)的权限控制吗?

举例讲,现有的permission可以实现对自定义model的所有实例增删改查的控制; 如果要实现分别将不同实例分配给不同的用户,请问要怎么实现呢?

**Comment by TianPangJi** [comment]
> 看了项目的权限控制这块,我的理解是可以实现model-level的权限控制,请问能实现实例级别或者对象级别(数据库行级别)的权限控制吗?
> 
> 举例讲,现有的permission可以实现对自定义model的所有实例增删改查的控制; 如果要实现分别将不同实例分配给不同的用户,请问要怎么实现呢?

我认为官方文档可以解决你的问题（对象级权限控制）：
https://www.django-rest-framework.org/api-guide/permissions/#object-level-permissions

**Comment by sdsy888** [comment]
谢谢,我研究一下.
