### ISSUE TITLE
依赖包文件版本需更新

### ISSUE THREAD

**Issue by KaroZeng** [TianPangJi/drf_admin#45]
The conflict is caused by:
    The user requested hyperlink==19.0.0
    autobahn 20.12.3 depends on hyperlink>=20.0.1

The conflict is caused by:
    The user requested urllib3==1.26.5
    requests 2.24.0 depends on urllib3!=1.25.0, !=1.25.1, <1.26 and >=1.21.1

**Comment by TianPangJi** [comment]
> The conflict is caused by:
> The user requested hyperlink==19.0.0
> autobahn 20.12.3 depends on hyperlink>=20.0.1
> 
> The conflict is caused by:
> The user requested urllib3==1.26.5
> requests 2.24.0 depends on urllib3!=1.25.0, !=1.25.1, <1.26 and >=1.21.1

感谢，已更新
