### ISSUE TITLE
JobsListCreateAPIView(ListCreateAPIView)类的问题

### ISSUE THREAD

**Issue by hzyddhuang** [TianPangJi/drf_admin#5]
该类下
    def get_serializer_class(self):
        if self.request.method.lower() == 'get'
这里self下是没有request属性的，运行报错。
可以修改为
class JobsListCreateViewSet(mixins.ListModelMixin, mixins.CreateModelMixin, GenericViewSet): 
    def get_serializer_class(self):
        if self.action == 'list':
            return JobsListSerializer

**Comment by TianPangJi** [comment]
感谢提出问题
JobsListCreateAPIView继承rest_framework的ListCreateAPIView，最后仍然是继承Django的View类。
get_serializer_class该方法，self是有request属性的，我这边并没有出现您提出的问题！运行未出现报错！！
如您那边扔出现问题，请提供错误详情，以便进行定位。

**Comment by TianPangJi** [comment]
> 该类下
> def get_serializer_class（s​​elf）：
> 如果self.request.method.lower（）=='get'
> 这里self下是没有请求属性的，运行报错。
> 可以修改为
> 类JobsListCreateViewSet（mixins.ListModelMixin，mixins.CreateModelMixin， GenericViewSet）：
> def get_serializer_class（s​​elf）：
> if self.action =='list'：
> 返回JobsListSerializer

感谢提出问题
JobsListCreateAPIView继承rest_framework的ListCreateAPIView，最后仍然是继承的Django的视图类。
get_serializer_class该方法，自我是有要求属性的，我这边并没有出现您提出的问题！运行未出现报错！
如您那边引发出现问题，请提供错误详情，刹车进行定位。

**Comment by hzyddhuang** [comment]
你好，我是添加了docs后，访问http://127.0.0.1:8080/docs/的时候报这个错的，AttributeError: 'NoneType' object has no attribute 'method'，你可以试下

**Comment by TianPangJi** [comment]
我这边并没有使用内置的API文档，而是使用的drf-yasg；

但也看了下你提出的这个问题，这个问题在DRF官方文档已给出了解释：
Note: By default include_docs_urls configures the underlying SchemaView to generate public schemas. This means that views will not be instantiated with a request instance. i.e. Inside the view self.request will be None.
To be compatible with this behaviour, methods (such as get_serializer or get_serializer_class etc.) which inspect self.request or, particularly, self.request.user may need to be adjusted to handle this case.
You may ensure views are given a request instance by calling include_docs_urls with public=False

[DRF官方链接](https://www.django-rest-framework.org/coreapi/from-documenting-your-api/#documentation-api-reference)；
个人建议不修改继承类，而是添加public属性。

**Comment by TianPangJi** [comment]
> 你好，我是添加了docs后，访问[http://127.0.0.1:8080/docs/的时候报这个错的，AttributeError](http://127.0.0.1:8080/docs/%E7%9A%84%E6%97%B6%E5%80%99%E6%8A%A5%E8%BF%99%E4%B8%AA%E9%94%99%E7%9A%84%EF%BC%8CAttributeError)：“ NoneType”对象没有属性“ method”，你可以试下

我这边并没有使用内置的API文档，而是使用的drf-yasg；

但也看了下你提出的这个问题，这个问题在DRF官方文档已给出了解释：
Note: By default include_docs_urls configures the underlying SchemaView to generate public schemas. This means that views will not be instantiated with a request instance. i.e. Inside the view self.request will be None.
To be compatible with this behaviour, methods (such as get_serializer or get_serializer_class etc.) which inspect self.request or, particularly, self.request.user may need to be adjusted to handle this case.
You may ensure views are given a request instance by calling include_docs_urls with public=False

[DRF官方链接](https://www.django-rest-framework.org/coreapi/from-documenting-your-api/#built-in-api-documentation)；
个人建议不修改继承类，而是添加public属性。
