### ISSUE TITLE
【建议】在文档中指定python具体版本

### ISSUE THREAD

**Issue by DingGuodong** [TianPangJi/drf_admin#9]
建议在 https://github.com/TianPangJi/drf_admin/blob/master/doc/run_drf.md 文档中指定python具体版本。
比如python3.x。

**Comment by TianPangJi** [comment]
> 建议在https://github.com/TianPangJi/drf_admin/blob/master/doc/run_drf.md文档中指定python具体版本。
> 比如python3.x。

感谢指出问题，之前没有考虑版本问题，先已添加

**Comment by DingGuodong** [comment]
感谢，辛苦！
